/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_authenticationType": "https://dzis17f45d.execute-api.eu-west-1.amazonaws.com/dev",
    "aws_appsync_apiKey": "0S93f8Wnwh741BrPwNKLn9j8wwyiLrMKa32VE2RP",
    "aws_cognito_identity_pool_id": "eu-west-1:767d461c-f2d1-4580-9aba-e40039c98dcc",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_mcUd9Olj6",
    "aws_user_pools_web_client_id": "3dbdm1ldmsa9mesagbodfdkv9v",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "amplifyreactapp-20240226163051-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://d34eqto6j75bmy.cloudfront.net"
};


export default awsmobile;
